name: Update JSON and TXT Files

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install -g json jq

      - name: Replace Text in JSON and TXT Files
        run: |
          # 处理 JSON 文件
          find . -name "*.json" | while read -r file; do
            echo "Processing $file"
            # 检查是否为有效的 JSON 文件
            if jq empty "$file" 2>/dev/null; then
              # 处理有效 JSON 文件，替换链接
              json -I -f "$file" -e 'Object.keys(this).forEach(key => { if (typeof this[key] === "string") { this[key] = this[key].replace("https://gitdl.cn", "https://ghp.ci"); this[key] = this[key].replace("https://raw.githubusercontent.com/hjpwyb/tvbox6/refs/heads/master/", "https://raw.githubusercontent.com/hjpwyb/tvbox6/refs/heads/master") } })'
            else
              # 如果是无效 JSON 文件，跳过
              echo "Skipping $file (invalid JSON)"
            fi
          done

          # 处理 TXT 文件
          find . -name "*.txt" | while read -r file; do
            echo "Processing $file"
            # 使用 sed 替换 .txt 文件中的两个链接
            sed -i 's|https://gitdl.cn|https://ghp.ci|g' "$file"
            sed -i 's|https://raw.githubusercontent.com/fish2018/tvbox/master/|https://raw.githubusercontent.com/hjpwyb/tvbox6/refs/heads/master|g' "$file"
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update JSON and TXT files to replace URLs" || echo "No changes to commit"
          git push
