name: Update JSON Files

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 添加手动触发功能

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install -g json

      - name: Replace Text in JSON Files
        run: |
          find . -name "*.json" | while read -r file; do
            echo "Processing $file"
            json -I -f "$file" -e 'Object.keys(this).forEach(key => { if (typeof this[key] === "string") this[key] = this[key].replace("https://gitdl.cn", "https://ghp.ci") })'
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update JSON files to use https://ghp.ci" || echo "No changes to commit"
          git push
